services:

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    ports:
      - "8889:3000"
    volumes:
      - gitea_data:/data
    networks:
      - jenkins-network
    environment:
      - GITEA__security__INSTALL_LOCK=true
      - GITEA__webhook__ALLOWED_HOST_LIST=*

  jenkins:
    build: ./jenkins
    container_name: jenkins
    ports:
      - "8888:8080"
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - jenkins-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home

networks:
  jenkins-network:
    driver: bridge

volumes:
  gitea_data:
  jenkins_home:
